onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mips_multi_cycle_tb/mips/dp/clk
add wave -noupdate /mips_multi_cycle_tb/mips/dp/reset
add wave -noupdate /mips_multi_cycle_tb/mips/dp/pcFF/en
add wave -noupdate /mips_multi_cycle_tb/mips/dp/pcFF/d
add wave -noupdate /mips_multi_cycle_tb/mips/dp/pcFF/q
add wave -noupdate /mips_multi_cycle_tb/mips/dp/pcmux/a
add wave -noupdate /mips_multi_cycle_tb/mips/dp/pcmux/b
add wave -noupdate /mips_multi_cycle_tb/mips/dp/pcmux/sel
add wave -noupdate /mips_multi_cycle_tb/mips/dp/pcmux/y
add wave -noupdate /mips_multi_cycle_tb/mips/dp/idmem/wrEn
add wave -noupdate /mips_multi_cycle_tb/mips/dp/idmem/addr
add wave -noupdate /mips_multi_cycle_tb/mips/dp/idmem/wrData
add wave -noupdate /mips_multi_cycle_tb/mips/dp/idmem/rdData
add wave -noupdate /mips_multi_cycle_tb/mips/dp/idmem/mem
add wave -noupdate /mips_multi_cycle_tb/mips/dp/instr_reg/en
add wave -noupdate /mips_multi_cycle_tb/mips/dp/instr_reg/d
add wave -noupdate /mips_multi_cycle_tb/mips/dp/instr_reg/q
add wave -noupdate /mips_multi_cycle_tb/mips/dp/data_reg/d
add wave -noupdate /mips_multi_cycle_tb/mips/dp/data_reg/q
add wave -noupdate /mips_multi_cycle_tb/mips/dp/OPCode
add wave -noupdate /mips_multi_cycle_tb/mips/dp/Funct
add wave -noupdate /mips_multi_cycle_tb/mips/dp/regDstmux/a
add wave -noupdate /mips_multi_cycle_tb/mips/dp/regDstmux/b
add wave -noupdate /mips_multi_cycle_tb/mips/dp/regDstmux/sel
add wave -noupdate /mips_multi_cycle_tb/mips/dp/regDstmux/y
add wave -noupdate /mips_multi_cycle_tb/mips/dp/memtoRegmux/a
add wave -noupdate /mips_multi_cycle_tb/mips/dp/memtoRegmux/b
add wave -noupdate /mips_multi_cycle_tb/mips/dp/memtoRegmux/sel
add wave -noupdate /mips_multi_cycle_tb/mips/dp/memtoRegmux/y
add wave -noupdate /mips_multi_cycle_tb/mips/dp/rf/rdAddr1
add wave -noupdate /mips_multi_cycle_tb/mips/dp/rf/rdAddr2
add wave -noupdate /mips_multi_cycle_tb/mips/dp/rf/wrAddr
add wave -noupdate /mips_multi_cycle_tb/mips/dp/rf/regWrite
add wave -noupdate /mips_multi_cycle_tb/mips/dp/rf/wrData
add wave -noupdate /mips_multi_cycle_tb/mips/dp/rf/rdData1
add wave -noupdate /mips_multi_cycle_tb/mips/dp/rf/rdData2
add wave -noupdate /mips_multi_cycle_tb/mips/dp/rf/mem
add wave -noupdate /mips_multi_cycle_tb/mips/dp/rfd1_reg/d
add wave -noupdate /mips_multi_cycle_tb/mips/dp/rfd1_reg/q
add wave -noupdate /mips_multi_cycle_tb/mips/dp/rfd2_reg/d
add wave -noupdate /mips_multi_cycle_tb/mips/dp/rfd2_reg/q
add wave -noupdate /mips_multi_cycle_tb/mips/dp/signext1/a
add wave -noupdate /mips_multi_cycle_tb/mips/dp/signext1/y
add wave -noupdate /mips_multi_cycle_tb/mips/dp/sl1/a
add wave -noupdate /mips_multi_cycle_tb/mips/dp/sl1/y
add wave -noupdate /mips_multi_cycle_tb/mips/dp/srcAmux/a
add wave -noupdate /mips_multi_cycle_tb/mips/dp/srcAmux/b
add wave -noupdate /mips_multi_cycle_tb/mips/dp/srcAmux/sel
add wave -noupdate /mips_multi_cycle_tb/mips/dp/srcAmux/y
add wave -noupdate /mips_multi_cycle_tb/mips/dp/srcBmux/a
add wave -noupdate /mips_multi_cycle_tb/mips/dp/srcBmux/b
add wave -noupdate /mips_multi_cycle_tb/mips/dp/srcBmux/c
add wave -noupdate /mips_multi_cycle_tb/mips/dp/srcBmux/d
add wave -noupdate /mips_multi_cycle_tb/mips/dp/srcBmux/sel
add wave -noupdate /mips_multi_cycle_tb/mips/dp/srcBmux/y
add wave -noupdate /mips_multi_cycle_tb/mips/dp/alu1/srcA
add wave -noupdate /mips_multi_cycle_tb/mips/dp/alu1/srcB
add wave -noupdate /mips_multi_cycle_tb/mips/dp/alu1/ALUCtrl
add wave -noupdate /mips_multi_cycle_tb/mips/dp/alu1/ALUResult
add wave -noupdate /mips_multi_cycle_tb/mips/dp/alu1/Z
add wave -noupdate /mips_multi_cycle_tb/mips/dp/aluRes_reg/d
add wave -noupdate /mips_multi_cycle_tb/mips/dp/aluRes_reg/q
add wave -noupdate /mips_multi_cycle_tb/mips/dp/resmux/a
add wave -noupdate /mips_multi_cycle_tb/mips/dp/resmux/b
add wave -noupdate /mips_multi_cycle_tb/mips/dp/resmux/c
add wave -noupdate /mips_multi_cycle_tb/mips/dp/resmux/d
add wave -noupdate /mips_multi_cycle_tb/mips/dp/resmux/sel
add wave -noupdate /mips_multi_cycle_tb/mips/dp/resmux/y
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/OPCode
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/MemtoReg
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/RegDst
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/IorD
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/ALUSrcA
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/PCSrc
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/ALUSrcB
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/IRWrite
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/MemWrite
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/PCWrite
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/Branch
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/RegWrite
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/ALUOp
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/currState
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/maindec/nextState
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/aludec/ALUOp
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/aludec/Funct
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/aludec/ALUControl
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/PCEn
add wave -noupdate /mips_multi_cycle_tb/mips/ctrlU/bz
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {398 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 297
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {307 ps} {403 ps}
